<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\PhoneCode;

class phoneCodeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $data = [
            ['phone'=>93, 'code'=>'AF','name'=> 'Afghanistan'],
            ['phone'=>358,'code'=> 'AX','name'=> 'Aland Islands'],
            ['phone'=>355,'code'=> 'AL','name'=> 'Albania'],
            ['phone'=>213,'code'=> 'DZ','name'=> 'Algeria'],
            ['phone'=>1684,'code'=> 'AS','name'=> 'American Samoa'],
            ['phone'=>376,'code'=> 'AD','name'=> 'Andorra'],
            ['phone'=>244,'code'=> 'AO','name'=> 'Angola'],
            ['phone'=>1264,'code'=> 'AI','name'=> 'Anguilla'],
            ['phone'=>672,'code'=> 'AQ','name'=> 'Antarctica'],
            ['phone'=> 1268,'code'=> 'AG','name'=> 'Antigua and Barbuda'],
            ['phone'=> 54,'code'=> 'AR','name'=> 'Argentina'],
            ['phone'=> 374,'code'=> 'AM','name'=> 'Armenia'],
            ['phone'=> 297,'code'=> 'AW','name'=> 'Aruba'],
            ['phone'=> 61,'code'=> 'AU','name'=> 'Australia'],
            ['phone'=> 43,'code'=> 'AT','name'=> 'Austria'],
            ['phone'=> 994,'code'=> 'AZ','name'=> 'Azerbaijan'],
            ['phone'=> 1242,'code'=> 'BS','name'=> 'Bahamas'],
            ['phone'=> 973,'code'=> 'BH','name'=> 'Bahrain'],
            ['phone'=> 880,'code'=> 'BD','name'=> 'Bangladesh'],
            ['phone'=> 1246,'code'=> 'BB','name'=> 'Barbados'],
            ['phone'=> 375,'code'=> 'BY','name'=> 'Belarus'],
            ['phone'=> 32,'code'=> 'BE','name'=> 'Belgium'],
            ['phone'=> 501,'code'=> 'BZ','name'=> 'Belize'],
            ['phone'=> 229,'code'=> 'BJ','name'=> 'Benin'],
            ['phone'=> 1441,'code'=> 'BM','name'=> 'Bermuda'],
            ['phone'=> 975,'code'=> 'BT','name'=> 'Bhutan'],
            ['phone'=> 591,'code'=> 'BO','name'=> 'Bolivia'],
            ['phone'=> 599,'code'=> 'BQ','name'=> 'Bonaire, Sint Eustatius and Saba'],
            ['phone'=> 387,'code'=> 'BA','name'=> 'Bosnia and Herzegovina'],
            ['phone'=> 267,'code'=> 'BW','name'=> 'Botswana'],
            ['phone'=> 55,'code'=> 'BV','name'=> 'Bouvet Island'],
            ['phone'=> 55,'code'=> 'BR','name'=> 'Brazil'],
            ['phone'=> 246,'code'=> 'IO','name'=> 'British Indian Ocean Territory'],
            ['phone'=> 673,'code'=> 'BN','name'=> 'Brunei Darussalam'],
            ['phone'=> 359,'code'=> 'BG','name'=> 'Bulgaria'],
            ['phone'=> 226,'code'=> 'BF','name'=> 'Burkina Faso'],
            ['phone'=> 257,'code'=> 'BI','name'=> 'Burundi'],
            ['phone'=> 855,'code'=> 'KH','name'=> 'Cambodia'],
            ['phone'=> 237,'code'=> 'CM','name'=> 'Cameroon'],
            ['phone'=> 1,'code'=> 'CA','name'=> 'Canada'],
            ['phone'=> 238,'code'=> 'CV','name'=> 'Cape Verde'],
            ['phone'=> 1345,'code'=> 'KY','name'=> 'Cayman Islands'],
            ['phone'=> 236,'code'=> 'CF','name'=> 'Central African Republic'],
            ['phone'=> 235,'code'=> 'TD','name'=> 'Chad'],
            ['phone'=> 56,'code'=> 'CL','name'=> 'Chile'],
            ['phone'=> 86,'code'=> 'CN','name'=> 'China'],
            ['phone'=> 61,'code'=> 'CX','name'=> 'Christmas Island'],
            ['phone'=> 672,'code'=> 'CC','name'=> 'Cocos'],
            ['phone'=> 57,'code'=> 'CO','name'=> 'Colombia'],
            ['phone'=> 269,'code'=> 'KM','name'=> 'Comoros'],
            ['phone'=> 242,'code'=> 'CG','name'=> 'Congo'],
            ['phone'=> 242,'code'=> 'CD','name'=> 'Congo, Democratic Republic of the Congo'],
            ['phone'=> 682,'code'=> 'CK','name'=> 'Cook Islands'],
            ['phone'=> 506,'code'=> 'CR','name'=> 'Costa Rica'],
            ['phone'=> 225,'code'=> 'CI','name'=> 'Cote D\'Ivoire'],
            ['phone'=> 385,'code'=> 'HR','name'=> 'Croatia'],
            ['phone'=> 53,'code'=> 'CU','name'=> 'Cuba'],
            ['phone'=> 599,'code'=> 'CW','name'=> 'Curacao'],
            ['phone'=> 357,'code'=> 'CY','name'=> 'Cyprus'],
            ['phone'=> 420,'code'=> 'CZ','name'=> 'Czech Republic'],
            ['phone'=> 45,'code'=> 'DK','name'=> 'Denmark'],
            ['phone'=> 253,'code'=> 'DJ','name'=> 'Djibouti'],
            ['phone'=> 1767,'code'=> 'DM','name'=> 'Dominica'],
            ['phone'=> 1809,'code'=> 'DO','name'=> 'Dominican Republic'],
            ['phone'=> 593,'code'=> 'EC','name'=> 'Ecuador'],
            ['phone'=> 20,'code'=> 'EG','name'=> 'Egypt'],
            ['phone'=> 503,'code'=> 'SV','name'=> 'El Salvador'],
            ['phone'=> 240,'code'=> 'GQ','name'=> 'Equatorial Guinea'],
            ['phone'=> 291,'code'=> 'ER','name'=> 'Eritrea'],
            ['phone'=> 372,'code'=> 'EE','name'=> 'Estonia'],
            ['phone'=> 251,'code'=> 'ET','name'=> 'Ethiopia'],
            ['phone'=> 500,'code'=> 'FK','name'=> 'Falkland Islands'],
            ['phone'=> 298,'code'=> 'FO','name'=> 'Faroe Islands'],
            ['phone'=> 679,'code'=> 'FJ','name'=> 'Fiji'],
            ['phone'=> 358,'code'=> 'FI','name'=> 'Finland'],
            ['phone'=> 33,'code'=> 'FR','name'=> 'France'],
            ['phone'=> 594,'code'=> 'GF','name'=> 'French Guiana'],
            ['phone'=> 689,'code'=> 'PF','name'=> 'French Polynesia'],
            ['phone'=> 262,'code'=> 'TF','name'=> 'French Southern Territories'],
            ['phone'=> 241,'code'=> 'GA','name'=> 'Gabon'],
            ['phone'=> 220,'code'=> 'GM','name'=> 'Gambia'],
            ['phone'=> 995,'code'=> 'GE','name'=> 'Georgia'],
            ['phone'=> 49,'code'=> 'DE','name'=> 'Germany'],
            ['phone'=> 233,'code'=> 'GH','name'=> 'Ghana'],
            ['phone'=> 350,'code'=> 'GI','name'=> 'Gibraltar'],
            ['phone'=> 30,'code'=> 'GR','name'=> 'Greece'],
            ['phone'=> 299,'code'=> 'GL','name'=> 'Greenland'],
            ['phone'=> 1473,'code'=> 'GD','name'=> 'Grenada'],
            ['phone'=> 590,'code'=> 'GP','name'=> 'Guadeloupe'],
            ['phone'=> 1671,'code'=> 'GU','name'=> 'Guam'],
            ['phone'=> 502,'code'=> 'GT','name'=> 'Guatemala'],
            ['phone'=> 44,'code'=> 'GG','name'=> 'Guernsey'],
            ['phone'=> 224,'code'=> 'GN','name'=> 'Guinea'],
            ['phone'=> 245,'code'=> 'GW','name'=> 'Guinea-Bissau'],
            ['phone'=> 592,'code'=> 'GY','name'=> 'Guyana'],
            ['phone'=> 509,'code'=> 'HT','name'=> 'Haiti'],
            ['phone'=> 0,'code'=> 'HM','name'=> 'Heard Island and Mcdonald Islands'],
            ['phone'=> 39,'code'=> 'VA','name'=> 'Holy See'],
            ['phone'=> 504,'code'=> 'HN','name'=> 'Honduras'],
            ['phone'=> 852,'code'=> 'HK','name'=> 'Hong Kong'],
            ['phone'=> 36,'code'=> 'HU','name'=> 'Hungary'],
            ['phone'=> 354,'code'=> 'IS','name'=> 'Iceland'],
            ['phone'=> 91,'code'=> 'IN','name'=> 'India'],
            ['phone'=> 62,'code'=> 'ID','name'=> 'Indonesia'],
            ['phone'=> 98,'code'=> 'IR','name'=> 'Iran, Islamic Republic of'],
            ['phone'=> 964,'code'=> 'IQ','name'=> 'Iraq'],
            ['phone'=> 353,'code'=> 'IE','name'=> 'Ireland'],
            ['phone'=> 44,'code'=> 'IM','name'=> 'Isle of Man'],
            ['phone'=> 972,'code'=> 'IL','name'=> 'Israel'],
            ['phone'=> 39,'code'=> 'IT','name'=> 'Italy'],
            ['phone'=> 1876,'code'=> 'JM','name'=> 'Jamaica'],
            ['phone'=> 81,'code'=> 'JP','name'=> 'Japan'],
            ['phone'=> 44,'code'=> 'JE','name'=> 'Jersey'],
            ['phone'=> 962,'code'=> 'JO','name'=> 'Jordan'],
            ['phone'=> 7,'code'=> 'KZ','name'=> 'Kazakhstan'],
            ['phone'=> 254,'code'=> 'KE','name'=> 'Kenya'],
            ['phone'=> 686,'code'=> 'KI','name'=> 'Kiribati'],
            ['phone'=> 850,'code'=> 'KP','name'=> 'Korea, Democratic People\'s Republic of'],
            ['phone'=> 82,'code'=> 'KR','name'=> 'Korea, Republic of'],
            ['phone'=> 381,'code'=> 'XK','name'=> 'Kosovo'],
            ['phone'=> 965,'code'=> 'KW','name'=> 'Kuwait'],
            ['phone'=> 996,'code'=> 'KG','name'=> 'Kyrgyzstan'],
            ['phone'=> 856,'code'=> 'LA','name'=> 'Lao People\'s Democratic Republic'],
            ['phone'=> 371,'code'=> 'LV','name'=> 'Latvia'],
            ['phone'=> 961,'code'=> 'LB','name'=> 'Lebanon'],
            ['phone'=> 266,'code'=> 'LS','name'=> 'Lesotho'],
            ['phone'=> 231,'code'=> 'LR','name'=> 'Liberia'],
            ['phone'=> 218,'code'=> 'LY','name'=> 'Libyan Arab Jamahiriya'],
            ['phone'=> 423,'code'=> 'LI','name'=> 'Liechtenstein'],
            ['phone'=> 370,'code'=> 'LT','name'=> 'Lithuania'],
            ['phone'=> 352,'code'=> 'LU','name'=> 'Luxembourg'],
            ['phone'=> 853,'code'=> 'MO','name'=> 'Macao'],
            ['phone'=> 389,'code'=> 'MK','name'=> 'Macedonia, the Former Yugoslav Republic of'],
            ['phone'=> 261,'code'=> 'MG','name'=> 'Madagascar'],
            ['phone'=> 265,'code'=> 'MW','name'=> 'Malawi'],
            ['phone'=> 60,'code'=> 'MY','name'=> 'Malaysia'],
            ['phone'=> 960,'code'=> 'MV','name'=> 'Maldives'],
            ['phone'=> 223,'code'=> 'ML','name'=> 'Mali'],
            ['phone'=> 356,'code'=> 'MT','name'=> 'Malta'],
            ['phone'=> 692,'code'=> 'MH','name'=> 'Marshall Islands'],
            ['phone'=> 596,'code'=> 'MQ','name'=> 'Martinique'],
            ['phone'=> 222,'code'=> 'MR','name'=> 'Mauritania'],
            ['phone'=> 230,'code'=> 'MU','name'=> 'Mauritius'],
            ['phone'=> 269,'code'=> 'YT','name'=> 'Mayotte'],
            ['phone'=> 52,'code'=> 'MX','name'=> 'Mexico'],
            ['phone'=> 691,'code'=> 'FM','name'=> 'Micronesia, Federated States of'],
            ['phone'=> 373,'code'=> 'MD','name'=> 'Moldova, Republic of'],
            ['phone'=> 377,'code'=> 'MC','name'=> 'Monaco'],
            ['phone'=> 976,'code'=> 'MN','name'=> 'Mongolia'],
            ['phone'=> 382,'code'=> 'ME','name'=> 'Montenegro'],
            ['phone'=> 1664,'code'=> 'MS','name'=> 'Montserrat'],
            ['phone'=> 212,'code'=> 'MA','name'=> 'Morocco'],
            ['phone'=> 258,'code'=> 'MZ','name'=> 'Mozambique'],
            ['phone'=> 95,'code'=> 'MM','name'=> 'Myanmar'],
            ['phone'=> 264,'code'=> 'NA','name'=> 'Namibia'],
            ['phone'=> 674,'code'=> 'NR','name'=> 'Nauru'],
            ['phone'=> 977,'code'=> 'NP','name'=> 'Nepal'],
            ['phone'=> 31,'code'=> 'NL','name'=> 'Netherlands'],
            ['phone'=> 599,'code'=> 'AN','name'=> 'Netherlands Antilles'],
            ['phone'=> 687,'code'=> 'NC','name'=> 'New Caledonia'],
            ['phone'=> 64,'code'=> 'NZ','name'=> 'New Zealand'],
            ['phone'=> 505,'code'=> 'NI','name'=> 'Nicaragua'],
            ['phone'=> 227,'code'=> 'NE','name'=> 'Niger'],
            ['phone'=> 234,'code'=> 'NG','name'=> 'Nigeria'],
            ['phone'=> 683,'code'=> 'NU','name'=> 'Niue'],
            ['phone'=> 672,'code'=> 'NF','name'=> 'Norfolk Island'],
            ['phone'=> 1670,'code'=> 'MP','name'=> 'Northern Mariana Islands'],
            ['phone'=> 47,'code'=> 'NO','name'=> 'Norway'],
            ['phone'=> 968,'code'=> 'OM','name'=> 'Oman'],
            ['phone'=> 92,'code'=> 'PK','name'=> 'Pakistan'],
            ['phone'=> 680,'code'=> 'PW','name'=> 'Palau'],
            ['phone'=> 970,'code'=> 'PS','name'=> 'Palestinian Territory, Occupied'],
            ['phone'=> 507,'code'=> 'PA','name'=> 'Panama'],
            ['phone'=> 675,'code'=> 'PG','name'=> 'Papua New Guinea'],
            ['phone'=> 595,'code'=> 'PY','name'=> 'Paraguay'],
            ['phone'=> 51,'code'=> 'PE','name'=> 'Peru'],
            ['phone'=> 63,'code'=> 'PH','name'=> 'Philippines'],
            ['phone'=> 64,'code'=> 'PN','name'=> 'Pitcairn'],
            ['phone'=> 48,'code'=> 'PL','name'=> 'Poland'],
            ['phone'=> 351,'code'=> 'PT','name'=> 'Portugal'],
            ['phone'=> 1787,'code'=> 'PR','name'=> 'Puerto Rico'],
            ['phone'=> 974,'code'=> 'QA','name'=> 'Qatar'],
            ['phone'=> 262,'code'=> 'RE','name'=> 'Reunion'],
            ['phone'=> 40,'code'=> 'RO','name'=> 'Romania'],
            ['phone'=> 70,'code'=> 'RU','name'=> 'Russian Federation'],
            ['phone'=> 250,'code'=> 'RW','name'=> 'Rwanda'],
            ['phone'=> 590,'code'=> 'BL','name'=> 'Saint Barthelemy'],
            ['phone'=> 290,'code'=> 'SH','name'=> 'Saint Helena'],
            ['phone'=> 1869,'code'=> 'KN','name'=> 'Saint Kitts and Nevis'],
            ['phone'=> 1758,'code'=> 'LC','name'=> 'Saint Lucia'],
            ['phone'=> 590,'code'=> 'MF','name'=> 'Saint Martin'],
            ['phone'=> 508,'code'=> 'PM','name'=> 'Saint Pierre and Miquelon'],
            ['phone'=> 1784,'code'=> 'VC','name'=> 'Saint Vincent and the Grenadines'],
            ['phone'=> 684,'code'=> 'WS','name'=> 'Samoa'],
            ['phone'=> 378,'code'=> 'SM','name'=> 'San Marino'],
            ['phone'=> 239,'code'=> 'ST','name'=> 'Sao Tome and Principe'],
            ['phone'=> 966,'code'=> 'SA','name'=> 'Saudi Arabia'],
            ['phone'=> 221,'code'=> 'SN','name'=> 'Senegal'],
            ['phone'=> 381,'code'=> 'RS','name'=> 'Serbia'],
            ['phone'=> 381,'code'=> 'CS','name'=> 'Serbia and Montenegro'],
            ['phone'=> 248,'code'=> 'SC','name'=> 'Seychelles'],
            ['phone'=> 232,'code'=> 'SL','name'=> 'Sierra Leone'],
            ['phone'=> 65,'code'=> 'SG','name'=> 'Singapore'],
            ['phone'=> 721,'code'=> 'SX','name'=> 'Sint Maarten'],
            ['phone'=> 421,'code'=> 'SK','name'=> 'Slovakia'],
            ['phone'=> 386,'code'=> 'SI','name'=> 'Slovenia'],
            ['phone'=> 677,'code'=> 'SB','name'=> 'Solomon Islands'],
            ['phone'=> 252,'code'=> 'SO','name'=> 'Somalia'],
            ['phone'=> 27,'code'=> 'ZA','name'=> 'South Africa'],
            ['phone'=> 500,'code'=> 'GS','name'=> 'South Georgia and the South Sandwich Islands'],
            ['phone'=> 211,'code'=> 'SS','name'=> 'South Sudan'],
            ['phone'=> 34,'code'=> 'ES','name'=> 'Spain'],
            ['phone'=> 94,'code'=> 'LK','name'=> 'Sri Lanka'],
            ['phone'=> 249,'code'=> 'SD','name'=> 'Sudan'],
            ['phone'=> 597,'code'=> 'SR','name'=> 'Suriname'],
            ['phone'=> 47,'code'=> 'SJ','name'=> 'Svalbard and Jan Mayen'],
            ['phone'=> 268,'code'=> 'SZ','name'=> 'Swaziland'],
            ['phone'=> 46,'code'=> 'SE','name'=> 'Sweden'],
            ['phone'=> 41,'code'=> 'CH','name'=> 'Switzerland'],
            ['phone'=> 963,'code'=> 'SY','name'=> 'Syrian Arab Republic'],
            ['phone'=> 886,'code'=> 'TW','name'=> 'Taiwan, Province of China'],
            ['phone'=> 992,'code'=> 'TJ','name'=> 'Tajikistan'],
            ['phone'=> 255,'code'=> 'TZ','name'=> 'Tanzania, United Republic of'],
            ['phone'=> 66,'code'=> 'TH','name'=> 'Thailand'],
            ['phone'=> 670,'code'=> 'TL','name'=> 'Timor-Leste'],
            ['phone'=> 228,'code'=> 'TG','name'=> 'Togo'],
            ['phone'=> 690,'code'=> 'TK','name'=> 'Tokelau'],
            ['phone'=> 676,'code'=> 'TO','name'=> 'Tonga'],
            ['phone'=> 1868,'code'=> 'TT','name'=> 'Trinidad and Tobago'],
            ['phone'=> 216,'code'=> 'TN','name'=> 'Tunisia'],
            ['phone'=> 90,'code'=> 'TR','name'=> 'Turkey'],
            ['phone'=> 7370,'code'=> 'TM','name'=> 'Turkmenistan'],
            ['phone'=> 1649,'code'=> 'TC','name'=> 'Turks and Caicos Islands'],
            ['phone'=> 688,'code'=> 'TV','name'=> 'Tuvalu'],
            ['phone'=> 256,'code'=> 'UG','name'=> 'Uganda'],
            ['phone'=> 380,'code'=> 'UA','name'=> 'Ukraine'],
            ['phone'=> 971,'code'=> 'AE','name'=> 'United Arab Emirates'],
            ['phone'=> 44,'code'=> 'GB','name'=> 'United Kingdom'],
            ['phone'=> 1,'code'=> 'US','name'=> 'United States'],
            ['phone'=> 598,'code'=> 'UY','name'=> 'Uruguay'],
            ['phone'=> 998,'code'=> 'UZ','name'=> 'Uzbekistan'],
            ['phone'=> 678,'code'=> 'VU','name'=> 'Vanuatu'],
            ['phone'=> 58,'code'=> 'VE','name'=> 'Venezuela'],
            ['phone'=> 84,'code'=> 'VN','name'=> 'Viet Nam'],
            ['phone'=> 1284,'code'=> 'VG','name'=> 'Virgin Islands, British'],
            ['phone'=> 1340,'code'=> 'VI','name'=> 'Virgin Islands, U.s.'],
            ['phone'=> 681,'code'=> 'WF','name'=> 'Wallis and Futuna'],
            ['phone'=> 212,'code'=> 'EH','name'=> 'Western Sahara'],
            ['phone'=> 967,'code'=> 'YE','name'=> 'Yemen'],
            ['phone'=> 260,'code'=> 'ZM','name'=> 'Zambia'],
            ['phone'=> 263,'code'=> 'ZW','name'=> 'Zimbabwe'],
            ];

            foreach ($data as $item) {
                PhoneCode::updateOrCreate(['phone'=>$item['phone'],'code'=>$item['code'],'name' => $item['name']], $item);
            }
        }
}
